spring.application.name=riddle

spring.datasource.url=jdbc:mysql://localhost:3306/riddle_game?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ── JPA / Hibernate ──────────────────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

## AI - Ollama
#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.model=mistral

# In your environment or .env file
spring.ai.mistralai.api-key=${MISTRAL_API}

# ── JWT ───────────────────────────────────────────────────────────────────────
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=86400000

# ── Server ────────────────────────────────────────────────────────────────────
server.port=8080
